    <footer>
        
    </footer>

<?php
    // Load any required js files from the controller
    if(!empty($js)) {
        foreach($js as $filename) {
            printf('<script src="/js/%1$s"></script>', $filename);
        }
    }
?>

<?php if (!empty(\Flannel\Core\Config::get('ga.account_id'))) : ?>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo \Flannel\Core\Config::get('ga.account_id'); ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<?php echo \Flannel\Core\Config::get('ga.account_id'); ?>');
</script>
<?php endif; ?>
</body>
</html>
