<footer class="main-footer">
    <strong>Copyright &copy; 2016-<?php echo date("Y"); ?> <a href="https://flanneldevlab.com">Flannel Dev
            Lab</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> <?php echo \Flannel\Core\Config::get('env.version'); ?>
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/js/admin/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/js/admin/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/js/admin/plugins/bootstrap/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/js/admin/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/js/admin/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/js/admin/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/js/admin/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/js/admin/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/js/admin/plugins/moment/moment.min.js"></script>
<script src="/js/admin/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/js/admin/plugins/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/js/admin/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/js/admin/plugins/overlayScrollbars/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/admin/adminlte.js"></script>
</body>
</html>

