<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flannel Framework | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/admin/plugins/fontawesome/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/css/admin/plugins/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/css/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/css/admin/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/admin/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/css/admin/plugins/overlayScrollbars/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/css/admin/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="/css/admin/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="/admin/index" class="brand-link">
            <img src="/img/admin/flannel-logo.png" alt="Flannel Dev LabLogo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Flannel Framework</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="/admin" class="nav-link">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Dashboard
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-pencil-ruler"></i>
                            <p>
                                Theme Editor
                                <i class="right fas fa-angle-right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="/admin/theme/header" class="nav-link">
                                    <i class="far fa-heading nav-icon"></i>
                                    <p>Theme Header</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/footer" class="nav-link">
                                    <i class="far fa-shoe-prints nav-icon"></i>
                                    <p>Theme Footer</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/mainindex" class="nav-link">
                                    <i class="far fa-home nav-icon"></i>
                                    <p>Main Index</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/singlepost" class="nav-link">
                                    <i class="far fa-clipboard nav-icon"></i>
                                    <p>Single Post</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/notfound" class="nav-link">
                                    <i class="far fa-times-circle nav-icon"></i>
                                    <p>404 Template</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/stylesheet" class="nav-link">
                                    <i class="fab fa-css3-alt nav-icon"></i>
                                    <p>Stylesheet</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/admin/theme/javascript" class="nav-link">
                                    <i class="fab fa-js nav-icon"></i>
                                    <p>JavaScript</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="/admin/auth/logout" class="nav-link">
                            <i class="nav-icon fas fa-sign-out-alt"></i>
                            <p>
                                Logout
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
